name: easy_debug
description: A pure Dart in-app network debugger for Flutter. visualize Dio requests with a floating overlay, detailed inspection, and log management.
version: 0.0.1
# homepage: https://www.example.com
repository: https://github.com/JasonBoolean/flutter_easy_debug

environment:
  sdk: ^3.10.1
  flutter: '>=3.3.0'

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
